# Generated by Django 3.1.1 on 2021-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=611, primary_key=True, serialize=False),
        ),
    ]
