# Generated by Django 3.1.1 on 2021-03-29 13:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210329_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=users.models.from_611, primary_key=True, serialize=False),
        ),
    ]
