# Generated by Django 3.1.1 on 2021-03-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=100)),
                ('movie_logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
