# Generated by Django 3.1.1 on 2021-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_Recommender', '0002_auto_20210322_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
